---
- name: Download MediaWiki
  get_url:
    url: "{{ mediaWikiUrl }}"
    dest: "{{ userHome }}/{{ mediaWikiArchiveName }}"


- name: Download GPG signature
  get_url:
    url: "{{ gpgSignatureUrl }}"
    dest: "{{ userHome }}"



#- name: Creates directory
#  become: yes
 # file:
  #  path: /var/www/html/media
   # state: directory
   # mode: 0755

- name: Unarchive MediaWiki
  become: yes
  unarchive:
    src: "{{ userHome }}/{{ mediaWikiArchiveName }}"
    dest: "{{apacheHtmlLocation}}"
    remote_src: yes

- name: Adding Hard Link
  command: ln -s mediawiki-1.34.2/ mediawiki
  ignore_errors: True

- name: Renaming File
  become: yes
  command: mv mediawiki-1.34.2/ media
  args:
    chdir: "{{apacheHtmlLocation}}"
  ignore_errors: True

