---
  - name: install pip3
    become: yes
    yum: name=python3-pip state=present


  - name: Make sure pymysql is present
    become: yes #eded if the other tasks are not played as root
    pip:
      name: pymysql
      state: present

