---
# vars file for thoughtworks_practical
mediaWikiUrl: "https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.2.tar.gz"
gpgSignatureUrl: "https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.2.tar.gz.sig"
userHome: /home/ec2-user
mediaWikiArchiveName: mediawiki-1.34.2.tar.gz
locationInsideApache: media
apacheHtmlLocation: /var/www/html
dnfPackages:
    - httpd
    - php
    - php-mysqlnd
    - php-gd
    - php-xml
    - python3-firewall
    - firewalld
    - mariadb-server
    - mariadb
    - php-mbstring
    - php-json